// Code generated by "stringer -type=Ftype"; DO NOT EDIT.

package parse

import "strconv"

const (
	_Ftype_name_0 = "SelectUpdate"
	_Ftype_name_1 = "ReturnByteCode"
	_Ftype_name_2 = "ReturnFunction"
	_Ftype_name_3 = "ReturnValue"
	_Ftype_name_4 = "ReturnArray"
)

var (
	_Ftype_index_0 = [...]uint8{0, 6, 12}
)

func (i Ftype) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Ftype_name_0[_Ftype_index_0[i]:_Ftype_index_0[i+1]]
	case i == 4:
		return _Ftype_name_1
	case i == 8:
		return _Ftype_name_2
	case i == 16:
		return _Ftype_name_3
	case i == 32:
		return _Ftype_name_4
	default:
		return "Ftype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
