// Code generated by "stringer -type TokType"; DO NOT EDIT.

package parse

import "strconv"

const (
	_TokType_name_0 = "Syntax_TokenType_Token"
	_TokType_name_1 = "Kind_Token"
	_TokType_name_2 = "Data_Type_Token"
	_TokType_name_3 = "Data_Value_Token"
	_TokType_name_4 = "Pair_Value_Token"
	_TokType_name_5 = "Token_Collection"
	_TokType_name_6 = "Argument_Token"
	_TokType_name_7 = "Parameter_Token"
	_TokType_name_8 = "Tree_Node_Token"
)

var (
	_TokType_index_0 = [...]uint8{0, 12, 22}
)

func (i TokType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _TokType_name_0[_TokType_index_0[i]:_TokType_index_0[i+1]]
	case i == 4:
		return _TokType_name_1
	case i == 8:
		return _TokType_name_2
	case i == 16:
		return _TokType_name_3
	case i == 32:
		return _TokType_name_4
	case i == 64:
		return _TokType_name_5
	case i == 128:
		return _TokType_name_6
	case i == 256:
		return _TokType_name_7
	case i == 512:
		return _TokType_name_8
	default:
		return "TokType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
