// Code generated by "stringer -type Arity"; DO NOT EDIT.

package functions

import "strconv"

const _Arity_name = "NaryNullaryUnaryBinaryTernaryQuaternaryQuinarySenarySeptenaryOctonaryNovenaryDenary"

var _Arity_index = [...]uint8{0, 4, 11, 16, 22, 29, 39, 46, 52, 61, 69, 77, 83}

func (i Arity) String() string {
	i -= -1
	if i < 0 || i >= Arity(len(_Arity_index)-1) {
		return "Arity(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Arity_name[_Arity_index[i]:_Arity_index[i+1]]
}
