// Code generated by "stringer -type Arity"; DO NOT EDIT.

package functions

import "strconv"

const _Arity_name = "Constant_FunctionUnary_FunctionBinary_Function"

var _Arity_index = [...]uint8{0, 17, 31, 46}

func (i Arity) String() string {
	if i < 0 || i >= Arity(len(_Arity_index)-1) {
		return "Arity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Arity_name[_Arity_index[i]:_Arity_index[i+1]]
}
