// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package functions

import "strconv"

const _DataType_name = "ParameterArgumentReturnTupleListChainUniSetMuliSetAssocARecordLinkDLinkNodeTree"

var _DataType_map = map[DataType]string{
	1:    _DataType_name[0:9],
	2:    _DataType_name[9:17],
	4:    _DataType_name[17:23],
	8:    _DataType_name[23:28],
	16:   _DataType_name[28:32],
	32:   _DataType_name[32:37],
	64:   _DataType_name[37:43],
	128:  _DataType_name[43:50],
	256:  _DataType_name[50:56],
	512:  _DataType_name[56:62],
	1024: _DataType_name[62:66],
	2048: _DataType_name[66:71],
	4096: _DataType_name[71:75],
	8192: _DataType_name[75:79],
}

func (i DataType) String() string {
	if str, ok := _DataType_map[i]; ok {
		return str
	}
	return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
}
