// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package functions

import "strconv"

const _DataType_name = "PairVectorConstantUnaryBinaryNnaryTupleListChainUniSetMuliSetAssocARecordLinkDLinkNodeTree"

var _DataType_map = map[DataType]string{
	1:     _DataType_name[0:4],
	2:     _DataType_name[4:10],
	4:     _DataType_name[10:18],
	8:     _DataType_name[18:23],
	16:    _DataType_name[23:29],
	32:    _DataType_name[29:34],
	64:    _DataType_name[34:39],
	128:   _DataType_name[39:43],
	256:   _DataType_name[43:48],
	512:   _DataType_name[48:54],
	1024:  _DataType_name[54:61],
	2048:  _DataType_name[61:67],
	4096:  _DataType_name[67:73],
	8192:  _DataType_name[73:77],
	16384: _DataType_name[77:82],
	32768: _DataType_name[82:86],
	65536: _DataType_name[86:90],
}

func (i DataType) String() string {
	if str, ok := _DataType_map[i]; ok {
		return str
	}
	return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
}
