// Code generated by "stringer -type Equality"; DO NOT EDIT.

package functions

import "strconv"

const _Equality_name = "LesserEqualGreater"

var _Equality_index = [...]uint8{0, 6, 11, 18}

func (i Equality) String() string {
	i -= -1
	if i < 0 || i >= Equality(len(_Equality_index)-1) {
		return "Equality(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Equality_name[_Equality_index[i]:_Equality_index[i+1]]
}
