// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package functions

import "strconv"

const _Kind_name = "ValueInstancePolymorphArgumentParameterAttributAccessorGeneratorPairVectorTupleListUniSetMuliSetAssocARecordLinkDLinkNodeTreeHigherOrderInternal"

var _Kind_map = map[Kind]string{
	1:       _Kind_name[0:5],
	2:       _Kind_name[5:13],
	4:       _Kind_name[13:22],
	8:       _Kind_name[22:30],
	16:      _Kind_name[30:39],
	32:      _Kind_name[39:47],
	64:      _Kind_name[47:55],
	128:     _Kind_name[55:64],
	256:     _Kind_name[64:68],
	512:     _Kind_name[68:74],
	1024:    _Kind_name[74:79],
	2048:    _Kind_name[79:83],
	4096:    _Kind_name[83:89],
	8192:    _Kind_name[89:96],
	16384:   _Kind_name[96:102],
	32768:   _Kind_name[102:108],
	65536:   _Kind_name[108:112],
	131072:  _Kind_name[112:117],
	262144:  _Kind_name[117:121],
	524288:  _Kind_name[121:125],
	1048576: _Kind_name[125:136],
	2097152: _Kind_name[136:144],
}

func (i Kind) String() string {
	if str, ok := _Kind_map[i]; ok {
		return str
	}
	return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
}
