// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package functions

import "strconv"

const _Kind_name = "ValueParameterAttributAccessorDoubleVectorConstantUnaryBinaryNnaryTupleListUniSetMuliSetAssocARecordLinkDLinkNodeTreeInternal"

var _Kind_map = map[Kind]string{
	1:       _Kind_name[0:5],
	2:       _Kind_name[5:14],
	4:       _Kind_name[14:22],
	8:       _Kind_name[22:30],
	16:      _Kind_name[30:36],
	32:      _Kind_name[36:42],
	64:      _Kind_name[42:50],
	128:     _Kind_name[50:55],
	256:     _Kind_name[55:61],
	512:     _Kind_name[61:66],
	1024:    _Kind_name[66:71],
	2048:    _Kind_name[71:75],
	4096:    _Kind_name[75:81],
	8192:    _Kind_name[81:88],
	16384:   _Kind_name[88:94],
	32768:   _Kind_name[94:100],
	65536:   _Kind_name[100:104],
	131072:  _Kind_name[104:109],
	262144:  _Kind_name[109:113],
	524288:  _Kind_name[113:117],
	1048576: _Kind_name[117:125],
}

func (i Kind) String() string {
	if str, ok := _Kind_map[i]; ok {
		return str
	}
	return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
}
