// Code generated by "stringer -type Property"; DO NOT EDIT.

package functions

import "strconv"

const _Property_name = "PostFixInFixPreFixLesserEqualGreaterEagerLazyRight_BoundLeft_BoundMutableImutableEffectedPurePositionalNamedArgs"

var _Property_map = map[Property]string{
	1:     _Property_name[0:7],
	2:     _Property_name[7:12],
	4:     _Property_name[12:18],
	8:     _Property_name[18:24],
	16:    _Property_name[24:29],
	32:    _Property_name[29:36],
	64:    _Property_name[36:41],
	128:   _Property_name[41:45],
	256:   _Property_name[45:56],
	512:   _Property_name[56:66],
	1024:  _Property_name[66:73],
	2048:  _Property_name[73:81],
	4096:  _Property_name[81:89],
	8192:  _Property_name[89:93],
	16384: _Property_name[93:103],
	32768: _Property_name[103:112],
}

func (i Property) String() string {
	if str, ok := _Property_map[i]; ok {
		return str
	}
	return "Property(" + strconv.FormatInt(int64(i), 10) + ")"
}
