// Code generated by "stringer -type TokType"; DO NOT EDIT.

package functions

import "strconv"

const (
	_TokType_name_0 = "SyntaxSymbol"
	_TokType_name_1 = "Number"
	_TokType_name_2 = "D_Type"
	_TokType_name_3 = "H_Type"
)

var (
	_TokType_index_0 = [...]uint8{0, 6, 12}
)

func (i TokType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _TokType_name_0[_TokType_index_0[i]:_TokType_index_0[i+1]]
	case i == 4:
		return _TokType_name_1
	case i == 8:
		return _TokType_name_2
	case i == 16:
		return _TokType_name_3
	default:
		return "TokType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
