// Code generated by "stringer -type=TvKind"; DO NOT EDIT.

package functions

import "strconv"

const _TvKind_name = "FunctionNameFunctionTypeNativeTypeParamTypeClassType"

var _TvKind_index = [...]uint8{0, 12, 24, 34, 43, 52}

func (i TvKind) String() string {
	if i >= TvKind(len(_TvKind_index)-1) {
		return "TvKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TvKind_name[_TvKind_index[i]:_TvKind_index[i+1]]
}
