// Code generated by "stringer -type=TyArriOp"; DO NOT EDIT.

package functions

import "strconv"

const (
	_TyArriOp_name_0 = "AddSubstract"
	_TyArriOp_name_1 = "Multiply"
	_TyArriOp_name_2 = "Divide"
	_TyArriOp_name_3 = "Modulo"
)

var (
	_TyArriOp_index_0 = [...]uint8{0, 3, 12}
)

func (i TyArriOp) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _TyArriOp_name_0[_TyArriOp_index_0[i]:_TyArriOp_index_0[i+1]]
	case i == 4:
		return _TyArriOp_name_1
	case i == 8:
		return _TyArriOp_name_2
	case i == 16:
		return _TyArriOp_name_3
	default:
		return "TyArriOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
