// Code generated by "stringer -type=TyCon"; DO NOT EDIT.

package functions

import "strconv"

const _TyCon_name = "DataContructorExprContructorTypeContructor"

var _TyCon_index = [...]uint8{0, 14, 28, 42}

func (i TyCon) String() string {
	i -= -1
	if i < 0 || i >= TyCon(len(_TyCon_index)-1) {
		return "TyCon(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _TyCon_name[_TyCon_index[i]:_TyCon_index[i+1]]
}
