// Code generated by "stringer -type=TyExpr"; DO NOT EDIT.

package functions

import "strconv"

const (
	_TyExpr_name_0 = "TypeDefinitionTypeContructor"
	_TyExpr_name_1 = "DataContructor"
	_TyExpr_name_2 = "DataInstance"
	_TyExpr_name_3 = "FncDefinition"
	_TyExpr_name_4 = "FncApplication"
	_TyExpr_name_5 = "ThunkExpression"
	_TyExpr_name_6 = "CaseExpression"
)

var (
	_TyExpr_index_0 = [...]uint8{0, 14, 28}
)

func (i TyExpr) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _TyExpr_name_0[_TyExpr_index_0[i]:_TyExpr_index_0[i+1]]
	case i == 4:
		return _TyExpr_name_1
	case i == 8:
		return _TyExpr_name_2
	case i == 16:
		return _TyExpr_name_3
	case i == 32:
		return _TyExpr_name_4
	case i == 64:
		return _TyExpr_name_5
	case i == 128:
		return _TyExpr_name_6
	default:
		return "TyExpr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
