// Code generated by "stringer -type=TyFnc"; DO NOT EDIT.

package functions

import "strconv"

const _TyFnc_name = "TypeDataValueConstantGeneratorAccumulatorConstructorPropertyArgumentPatternElementLexicalSymbolArityIndexKeyTrueFalseUndecidedEqualLesserGreaterMinMaxSwitchCaseJustNoneOptionPolymorphEitherOrNaturalIntegerRealRatioLetterTextBytesVectorListSetPairEnumTupleRecordMonadStateIOParametric"

var _TyFnc_map = map[TyFnc]string{
	1:               _TyFnc_name[0:4],
	2:               _TyFnc_name[4:8],
	4:               _TyFnc_name[8:13],
	8:               _TyFnc_name[13:21],
	16:              _TyFnc_name[21:30],
	32:              _TyFnc_name[30:41],
	64:              _TyFnc_name[41:52],
	128:             _TyFnc_name[52:60],
	256:             _TyFnc_name[60:68],
	512:             _TyFnc_name[68:75],
	1024:            _TyFnc_name[75:82],
	2048:            _TyFnc_name[82:89],
	4096:            _TyFnc_name[89:95],
	8192:            _TyFnc_name[95:100],
	16384:           _TyFnc_name[100:105],
	32768:           _TyFnc_name[105:108],
	65536:           _TyFnc_name[108:112],
	131072:          _TyFnc_name[112:117],
	262144:          _TyFnc_name[117:126],
	524288:          _TyFnc_name[126:131],
	1048576:         _TyFnc_name[131:137],
	2097152:         _TyFnc_name[137:144],
	4194304:         _TyFnc_name[144:147],
	8388608:         _TyFnc_name[147:150],
	16777216:        _TyFnc_name[150:156],
	33554432:        _TyFnc_name[156:160],
	67108864:        _TyFnc_name[160:164],
	134217728:       _TyFnc_name[164:168],
	268435456:       _TyFnc_name[168:174],
	536870912:       _TyFnc_name[174:183],
	1073741824:      _TyFnc_name[183:189],
	2147483648:      _TyFnc_name[189:191],
	4294967296:      _TyFnc_name[191:198],
	8589934592:      _TyFnc_name[198:205],
	17179869184:     _TyFnc_name[205:209],
	34359738368:     _TyFnc_name[209:214],
	68719476736:     _TyFnc_name[214:220],
	137438953472:    _TyFnc_name[220:224],
	274877906944:    _TyFnc_name[224:229],
	549755813888:    _TyFnc_name[229:235],
	1099511627776:   _TyFnc_name[235:239],
	2199023255552:   _TyFnc_name[239:242],
	4398046511104:   _TyFnc_name[242:246],
	8796093022208:   _TyFnc_name[246:250],
	17592186044416:  _TyFnc_name[250:255],
	35184372088832:  _TyFnc_name[255:261],
	70368744177664:  _TyFnc_name[261:266],
	140737488355328: _TyFnc_name[266:271],
	281474976710656: _TyFnc_name[271:273],
	562949953421312: _TyFnc_name[273:283],
}

func (i TyFnc) String() string {
	if str, ok := _TyFnc_map[i]; ok {
		return str
	}
	return "TyFnc(" + strconv.FormatInt(int64(i), 10) + ")"
}
