// Code generated by "stringer -type=TyHigherOrder"; DO NOT EDIT.

package functions

import "strconv"

const _TyHigherOrder_name = "TypeDataConstructorClosureFunctionAccessorArgumentAttributParameterPredicateGeneratorUnboundOptionJustNoneOrIfElseTruthTrueFalseEnumCasePairListTupleUniSetMuliSetAssocVecRecordVectorDLinkLinkNodeTreeHigherOrder"

var _TyHigherOrder_map = map[TyHigherOrder]string{
	1:           _TyHigherOrder_name[0:4],
	2:           _TyHigherOrder_name[4:8],
	4:           _TyHigherOrder_name[8:19],
	8:           _TyHigherOrder_name[19:26],
	16:          _TyHigherOrder_name[26:34],
	32:          _TyHigherOrder_name[34:42],
	64:          _TyHigherOrder_name[42:50],
	128:         _TyHigherOrder_name[50:58],
	256:         _TyHigherOrder_name[58:67],
	512:         _TyHigherOrder_name[67:76],
	1024:        _TyHigherOrder_name[76:85],
	2048:        _TyHigherOrder_name[85:92],
	4096:        _TyHigherOrder_name[92:98],
	8192:        _TyHigherOrder_name[98:102],
	16384:       _TyHigherOrder_name[102:106],
	32768:       _TyHigherOrder_name[106:108],
	65536:       _TyHigherOrder_name[108:110],
	131072:      _TyHigherOrder_name[110:114],
	262144:      _TyHigherOrder_name[114:119],
	524288:      _TyHigherOrder_name[119:123],
	1048576:     _TyHigherOrder_name[123:128],
	2097152:     _TyHigherOrder_name[128:132],
	4194304:     _TyHigherOrder_name[132:136],
	8388608:     _TyHigherOrder_name[136:140],
	16777216:    _TyHigherOrder_name[140:144],
	33554432:    _TyHigherOrder_name[144:149],
	67108864:    _TyHigherOrder_name[149:155],
	134217728:   _TyHigherOrder_name[155:162],
	268435456:   _TyHigherOrder_name[162:170],
	536870912:   _TyHigherOrder_name[170:176],
	1073741824:  _TyHigherOrder_name[176:182],
	2147483648:  _TyHigherOrder_name[182:187],
	4294967296:  _TyHigherOrder_name[187:191],
	8589934592:  _TyHigherOrder_name[191:195],
	17179869184: _TyHigherOrder_name[195:199],
	34359738368: _TyHigherOrder_name[199:210],
}

func (i TyHigherOrder) String() string {
	if str, ok := _TyHigherOrder_map[i]; ok {
		return str
	}
	return "TyHigherOrder(" + strconv.FormatInt(int64(i), 10) + ")"
}
