// Code generated by "stringer -type=TyHigherOrder"; DO NOT EDIT.

package functions

import "strconv"

const _TyHigherOrder_name = "DataClosureFunctionAccessorArgumentAttributParameterPredicateGeneratorUnboundOptionJustNoneTrueFalseEnumCasePairListTupleUniSetMuliSetAssocVecRecordVectorDLinkLinkNodeTreeHigherOrder"

var _TyHigherOrder_map = map[TyHigherOrder]string{
	1:         _TyHigherOrder_name[0:4],
	2:         _TyHigherOrder_name[4:11],
	4:         _TyHigherOrder_name[11:19],
	8:         _TyHigherOrder_name[19:27],
	16:        _TyHigherOrder_name[27:35],
	32:        _TyHigherOrder_name[35:43],
	64:        _TyHigherOrder_name[43:52],
	128:       _TyHigherOrder_name[52:61],
	256:       _TyHigherOrder_name[61:70],
	512:       _TyHigherOrder_name[70:77],
	1024:      _TyHigherOrder_name[77:83],
	2048:      _TyHigherOrder_name[83:87],
	4096:      _TyHigherOrder_name[87:91],
	8192:      _TyHigherOrder_name[91:95],
	16384:     _TyHigherOrder_name[95:100],
	32768:     _TyHigherOrder_name[100:104],
	65536:     _TyHigherOrder_name[104:108],
	131072:    _TyHigherOrder_name[108:112],
	262144:    _TyHigherOrder_name[112:116],
	524288:    _TyHigherOrder_name[116:121],
	1048576:   _TyHigherOrder_name[121:127],
	2097152:   _TyHigherOrder_name[127:134],
	4194304:   _TyHigherOrder_name[134:142],
	8388608:   _TyHigherOrder_name[142:148],
	16777216:  _TyHigherOrder_name[148:154],
	33554432:  _TyHigherOrder_name[154:159],
	67108864:  _TyHigherOrder_name[159:163],
	134217728: _TyHigherOrder_name[163:167],
	268435456: _TyHigherOrder_name[167:171],
	536870912: _TyHigherOrder_name[171:182],
}

func (i TyHigherOrder) String() string {
	if str, ok := _TyHigherOrder_map[i]; ok {
		return str
	}
	return "TyHigherOrder(" + strconv.FormatInt(int64(i), 10) + ")"
}
