// Code generated by "stringer -type=TyHigherOrder"; DO NOT EDIT.

package functions

import "strconv"

const _TyHigherOrder_name = "ValueInstancePolymorphArgumentParameterAttributAccessorGeneratorPairVectorTupleListUniSetMuliSetAssocARecordLinkDLinkNodeTreeHigherOrderInternal"

var _TyHigherOrder_map = map[TyHigherOrder]string{
	1:       _TyHigherOrder_name[0:5],
	2:       _TyHigherOrder_name[5:13],
	4:       _TyHigherOrder_name[13:22],
	8:       _TyHigherOrder_name[22:30],
	16:      _TyHigherOrder_name[30:39],
	32:      _TyHigherOrder_name[39:47],
	64:      _TyHigherOrder_name[47:55],
	128:     _TyHigherOrder_name[55:64],
	256:     _TyHigherOrder_name[64:68],
	512:     _TyHigherOrder_name[68:74],
	1024:    _TyHigherOrder_name[74:79],
	2048:    _TyHigherOrder_name[79:83],
	4096:    _TyHigherOrder_name[83:89],
	8192:    _TyHigherOrder_name[89:96],
	16384:   _TyHigherOrder_name[96:102],
	32768:   _TyHigherOrder_name[102:108],
	65536:   _TyHigherOrder_name[108:112],
	131072:  _TyHigherOrder_name[112:117],
	262144:  _TyHigherOrder_name[117:121],
	524288:  _TyHigherOrder_name[121:125],
	1048576: _TyHigherOrder_name[125:136],
	2097152: _TyHigherOrder_name[136:144],
}

func (i TyHigherOrder) String() string {
	if str, ok := _TyHigherOrder_map[i]; ok {
		return str
	}
	return "TyHigherOrder(" + strconv.FormatInt(int64(i), 10) + ")"
}
