// Code generated by "stringer -type=TyKeyWord"; DO NOT EDIT.

package functions

import "strconv"

const _TyKeyWord_name = "Word_DoWord_InWord_OfWord_ConWord_LetWord_IfWord_ThenWord_ElseWord_CaseWord_WhereWord_DataWord_TypeWord_MutableWord_Otherwise"

var _TyKeyWord_index = [...]uint8{0, 7, 14, 21, 29, 37, 44, 53, 62, 71, 81, 90, 99, 111, 125}

func (i TyKeyWord) String() string {
	if i >= TyKeyWord(len(_TyKeyWord_index)-1) {
		return "TyKeyWord(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TyKeyWord_name[_TyKeyWord_index[i]:_TyKeyWord_index[i+1]]
}
