// Code generated by "stringer -type=TyKeyWord"; DO NOT EDIT.

package functions

import "strconv"

const _TyKeyWord_name = "Word_DoWord_InWord_OfWord_ConWord_LetWord_IfWord_ThenWord_ElseWord_CaseWord_WhereWord_DataWord_TypeWord_MutableWord_Otherwise"

var _TyKeyWord_map = map[TyKeyWord]string{
	0:    _TyKeyWord_name[0:7],
	1:    _TyKeyWord_name[7:14],
	4:    _TyKeyWord_name[14:21],
	8:    _TyKeyWord_name[21:29],
	16:   _TyKeyWord_name[29:37],
	32:   _TyKeyWord_name[37:44],
	64:   _TyKeyWord_name[44:53],
	128:  _TyKeyWord_name[53:62],
	256:  _TyKeyWord_name[62:71],
	512:  _TyKeyWord_name[71:81],
	1024: _TyKeyWord_name[81:90],
	2048: _TyKeyWord_name[90:99],
	4096: _TyKeyWord_name[99:111],
	8192: _TyKeyWord_name[111:125],
}

func (i TyKeyWord) String() string {
	if str, ok := _TyKeyWord_map[i]; ok {
		return str
	}
	return "TyKeyWord(" + strconv.FormatInt(int64(i), 10) + ")"
}
