// Code generated by "stringer -type TyKind"; DO NOT EDIT.

package functions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Kind_BitFlag-0]
	_ = x[Kind_Nat-1]
	_ = x[Kind_Fnc-2]
	_ = x[Kind_Key-3]
	_ = x[Kind_Sym-4]
	_ = x[Kind_Expr-5]
	_ = x[Kind_Prop-6]
	_ = x[Kind_Lex-7]
	_ = x[Kind_Opt-8]
	_ = x[Kind_Comp-255]
}

const (
	_TyKind_name_0 = "Kind_BitFlagKind_NatKind_FncKind_KeyKind_SymKind_ExprKind_PropKind_LexKind_Opt"
	_TyKind_name_1 = "Kind_Comp"
)

var (
	_TyKind_index_0 = [...]uint8{0, 12, 20, 28, 36, 44, 53, 62, 70, 78}
)

func (i TyKind) String() string {
	switch {
	case 0 <= i && i <= 8:
		return _TyKind_name_0[_TyKind_index_0[i]:_TyKind_index_0[i+1]]
	case i == 255:
		return _TyKind_name_1
	default:
		return "TyKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
