// Code generated by "stringer -type=TyLex"; DO NOT EDIT.

package functions

import "strconv"

const _TyLex_name = "Lex_NullLex_BlankLex_TabLex_NewLineLex_UnderscoreLex_AsteriskLex_FullstopLex_EllipsisLex_SubstractionLex_AdditionLex_SquareRootLex_DotLex_TimesLex_DotProductLex_CrossProductLex_DivisionLex_InfiniteLex_AndLex_OrLex_XorLex_EqualLex_UnequalLex_LesserLex_GreaterLex_LesserEqLex_GreaterEqLex_LeftParLex_RightParLex_LeftBraLex_RightBraLex_LeftCurLex_RightCurLex_LeftLaceLex_RightLaceLex_SingQuoteLex_DoubQuoteLex_BackTickLex_BackSlashLex_SlashLex_PipeLex_NotLex_DecrementLex_IncrementLex_TripEqualLex_RightArrowLex_LeftArrowLex_LeftFatArrowLex_RightFatArrowLex_DoubleFatArrowLex_SequenceLex_SequenceRevLex_DoubColLex_ApplicationLex_LambdaLex_FunctionLex_PolymorphLex_MonadLex_ParameterLex_IntegralLex_SubSetLex_EmptySetLex_Pi"

var _TyLex_map = map[TyLex]string{
	0:                   _TyLex_name[0:8],
	1:                   _TyLex_name[8:17],
	4:                   _TyLex_name[17:24],
	8:                   _TyLex_name[24:35],
	16:                  _TyLex_name[35:49],
	32:                  _TyLex_name[49:61],
	64:                  _TyLex_name[61:73],
	128:                 _TyLex_name[73:85],
	256:                 _TyLex_name[85:101],
	512:                 _TyLex_name[101:113],
	1024:                _TyLex_name[113:127],
	2048:                _TyLex_name[127:134],
	4096:                _TyLex_name[134:143],
	8192:                _TyLex_name[143:157],
	16384:               _TyLex_name[157:173],
	32768:               _TyLex_name[173:185],
	65536:               _TyLex_name[185:197],
	131072:              _TyLex_name[197:204],
	262144:              _TyLex_name[204:210],
	524288:              _TyLex_name[210:217],
	1048576:             _TyLex_name[217:226],
	2097152:             _TyLex_name[226:237],
	4194304:             _TyLex_name[237:247],
	8388608:             _TyLex_name[247:258],
	16777216:            _TyLex_name[258:270],
	33554432:            _TyLex_name[270:283],
	67108864:            _TyLex_name[283:294],
	134217728:           _TyLex_name[294:306],
	268435456:           _TyLex_name[306:317],
	536870912:           _TyLex_name[317:329],
	1073741824:          _TyLex_name[329:340],
	2147483648:          _TyLex_name[340:352],
	4294967296:          _TyLex_name[352:364],
	8589934592:          _TyLex_name[364:377],
	17179869184:         _TyLex_name[377:390],
	34359738368:         _TyLex_name[390:403],
	68719476736:         _TyLex_name[403:415],
	137438953472:        _TyLex_name[415:428],
	274877906944:        _TyLex_name[428:437],
	549755813888:        _TyLex_name[437:445],
	1099511627776:       _TyLex_name[445:452],
	2199023255552:       _TyLex_name[452:465],
	4398046511104:       _TyLex_name[465:478],
	8796093022208:       _TyLex_name[478:491],
	17592186044416:      _TyLex_name[491:505],
	35184372088832:      _TyLex_name[505:518],
	70368744177664:      _TyLex_name[518:534],
	140737488355328:     _TyLex_name[534:551],
	281474976710656:     _TyLex_name[551:569],
	562949953421312:     _TyLex_name[569:581],
	1125899906842624:    _TyLex_name[581:596],
	2251799813685248:    _TyLex_name[596:607],
	4503599627370496:    _TyLex_name[607:622],
	9007199254740992:    _TyLex_name[622:632],
	18014398509481984:   _TyLex_name[632:644],
	36028797018963968:   _TyLex_name[644:657],
	72057594037927936:   _TyLex_name[657:666],
	144115188075855872:  _TyLex_name[666:679],
	288230376151711744:  _TyLex_name[679:691],
	576460752303423488:  _TyLex_name[691:701],
	1152921504606846976: _TyLex_name[701:713],
	2305843009213693952: _TyLex_name[713:719],
}

func (i TyLex) String() string {
	if str, ok := _TyLex_map[i]; ok {
		return str
	}
	return "TyLex(" + strconv.FormatInt(int64(i), 10) + ")"
}
