// Code generated by "stringer -type=TyLex"; DO NOT EDIT.

package functions

import "strconv"

const _TyLex_name = "NullBlankTabNewLineUnderscoreAsteriskFullstopEllipsisSubstractionAdditionSquareRootDotTimesDotProductCrossProductDivisionInfiniteAndOrXorEqualUnequalLesserGreaterLesserEqGreaterEqLeftParRightParLeftBraRightBraLeftCurRightCurLeftLaceRightLaceSingQuoteDoubQuoteBackTickBackSlashSlashPipeNotDecrementIncrementTripEqualRightArrowLeftArrowLeftFatArrowRightFatArrowDoubleFatArrowSequenceSequenceRevDoubColApplicationLambdaFunctionPolymorphMonadParameterIntegralSubSetEmptySetPi"

var _TyLex_map = map[TyLex]string{
	0:                   _TyLex_name[0:4],
	1:                   _TyLex_name[4:9],
	4:                   _TyLex_name[9:12],
	8:                   _TyLex_name[12:19],
	16:                  _TyLex_name[19:29],
	32:                  _TyLex_name[29:37],
	64:                  _TyLex_name[37:45],
	128:                 _TyLex_name[45:53],
	256:                 _TyLex_name[53:65],
	512:                 _TyLex_name[65:73],
	1024:                _TyLex_name[73:83],
	2048:                _TyLex_name[83:86],
	4096:                _TyLex_name[86:91],
	8192:                _TyLex_name[91:101],
	16384:               _TyLex_name[101:113],
	32768:               _TyLex_name[113:121],
	65536:               _TyLex_name[121:129],
	131072:              _TyLex_name[129:132],
	262144:              _TyLex_name[132:134],
	524288:              _TyLex_name[134:137],
	1048576:             _TyLex_name[137:142],
	2097152:             _TyLex_name[142:149],
	4194304:             _TyLex_name[149:155],
	8388608:             _TyLex_name[155:162],
	16777216:            _TyLex_name[162:170],
	33554432:            _TyLex_name[170:179],
	67108864:            _TyLex_name[179:186],
	134217728:           _TyLex_name[186:194],
	268435456:           _TyLex_name[194:201],
	536870912:           _TyLex_name[201:209],
	1073741824:          _TyLex_name[209:216],
	2147483648:          _TyLex_name[216:224],
	4294967296:          _TyLex_name[224:232],
	8589934592:          _TyLex_name[232:241],
	17179869184:         _TyLex_name[241:250],
	34359738368:         _TyLex_name[250:259],
	68719476736:         _TyLex_name[259:267],
	137438953472:        _TyLex_name[267:276],
	274877906944:        _TyLex_name[276:281],
	549755813888:        _TyLex_name[281:285],
	1099511627776:       _TyLex_name[285:288],
	2199023255552:       _TyLex_name[288:297],
	4398046511104:       _TyLex_name[297:306],
	8796093022208:       _TyLex_name[306:315],
	17592186044416:      _TyLex_name[315:325],
	35184372088832:      _TyLex_name[325:334],
	70368744177664:      _TyLex_name[334:346],
	140737488355328:     _TyLex_name[346:359],
	281474976710656:     _TyLex_name[359:373],
	562949953421312:     _TyLex_name[373:381],
	1125899906842624:    _TyLex_name[381:392],
	2251799813685248:    _TyLex_name[392:399],
	4503599627370496:    _TyLex_name[399:410],
	9007199254740992:    _TyLex_name[410:416],
	18014398509481984:   _TyLex_name[416:424],
	36028797018963968:   _TyLex_name[424:433],
	72057594037927936:   _TyLex_name[433:438],
	144115188075855872:  _TyLex_name[438:447],
	288230376151711744:  _TyLex_name[447:455],
	576460752303423488:  _TyLex_name[455:461],
	1152921504606846976: _TyLex_name[461:469],
	2305843009213693952: _TyLex_name[469:471],
}

func (i TyLex) String() string {
	if str, ok := _TyLex_map[i]; ok {
		return str
	}
	return "TyLex(" + strconv.FormatInt(int64(i), 10) + ")"
}
