// Code generated by "stringer -type TyLex"; DO NOT EDIT.

package functions

import "strconv"

const _TyLex_name = "Lex_NullLex_BlankLex_TabLex_NewLineLex_UnderscoreLex_AsteriskLex_FullstopLex_EllipsisLex_NegativeLex_PositiveLex_SquareRootLex_DotLex_TimesLex_DotProductLex_CrossProductLex_DivisionLex_InfiniteLex_AndLex_OrLex_XorLex_EqualLex_UnequalLex_LesserLex_GreaterLex_LesserEqLex_GreaterEqLex_LeftParLex_RightParLex_LeftBraLex_RightBraLex_LeftCurLex_RightCurLex_LeftLaceLex_RightLaceLex_SingQuoteLex_DoubQuoteLex_BackTickLex_BackSlashLex_SlashLex_PipeLex_NotLex_DecrementLex_IncrementLex_TripEqualLex_RightArrowLex_LeftArrowLex_LeftFatArrowLex_RightFatArrowLex_DoubleFatArrowLex_SequenceLex_SequenceRevLex_DoubColLex_ApplicationLex_LambdaLex_FunctionLex_PolymorphLex_MonadLex_ParameterLex_IntegralLex_SubSetLex_EmptySetLex_Pi"

var _TyLex_map = map[TyLex]string{
	0:                   _TyLex_name[0:8],
	1:                   _TyLex_name[8:17],
	4:                   _TyLex_name[17:24],
	8:                   _TyLex_name[24:35],
	16:                  _TyLex_name[35:49],
	32:                  _TyLex_name[49:61],
	64:                  _TyLex_name[61:73],
	128:                 _TyLex_name[73:85],
	256:                 _TyLex_name[85:97],
	512:                 _TyLex_name[97:109],
	1024:                _TyLex_name[109:123],
	2048:                _TyLex_name[123:130],
	4096:                _TyLex_name[130:139],
	8192:                _TyLex_name[139:153],
	16384:               _TyLex_name[153:169],
	32768:               _TyLex_name[169:181],
	65536:               _TyLex_name[181:193],
	131072:              _TyLex_name[193:200],
	262144:              _TyLex_name[200:206],
	524288:              _TyLex_name[206:213],
	1048576:             _TyLex_name[213:222],
	2097152:             _TyLex_name[222:233],
	4194304:             _TyLex_name[233:243],
	8388608:             _TyLex_name[243:254],
	16777216:            _TyLex_name[254:266],
	33554432:            _TyLex_name[266:279],
	67108864:            _TyLex_name[279:290],
	134217728:           _TyLex_name[290:302],
	268435456:           _TyLex_name[302:313],
	536870912:           _TyLex_name[313:325],
	1073741824:          _TyLex_name[325:336],
	2147483648:          _TyLex_name[336:348],
	4294967296:          _TyLex_name[348:360],
	8589934592:          _TyLex_name[360:373],
	17179869184:         _TyLex_name[373:386],
	34359738368:         _TyLex_name[386:399],
	68719476736:         _TyLex_name[399:411],
	137438953472:        _TyLex_name[411:424],
	274877906944:        _TyLex_name[424:433],
	549755813888:        _TyLex_name[433:441],
	1099511627776:       _TyLex_name[441:448],
	2199023255552:       _TyLex_name[448:461],
	4398046511104:       _TyLex_name[461:474],
	8796093022208:       _TyLex_name[474:487],
	17592186044416:      _TyLex_name[487:501],
	35184372088832:      _TyLex_name[501:514],
	70368744177664:      _TyLex_name[514:530],
	140737488355328:     _TyLex_name[530:547],
	281474976710656:     _TyLex_name[547:565],
	562949953421312:     _TyLex_name[565:577],
	1125899906842624:    _TyLex_name[577:592],
	2251799813685248:    _TyLex_name[592:603],
	4503599627370496:    _TyLex_name[603:618],
	9007199254740992:    _TyLex_name[618:628],
	18014398509481984:   _TyLex_name[628:640],
	36028797018963968:   _TyLex_name[640:653],
	72057594037927936:   _TyLex_name[653:662],
	144115188075855872:  _TyLex_name[662:675],
	288230376151711744:  _TyLex_name[675:687],
	576460752303423488:  _TyLex_name[687:697],
	1152921504606846976: _TyLex_name[697:709],
	2305843009213693952: _TyLex_name[709:715],
}

func (i TyLex) String() string {
	if str, ok := _TyLex_map[i]; ok {
		return str
	}
	return "TyLex(" + strconv.FormatInt(int64(i), 10) + ")"
}
