// Code generated by "stringer -type TyProp"; DO NOT EDIT.

package functions

import "strconv"

const _TyProp_name = "DefaultPostFixPreFixInFixAtomicThunkEagerLazyRightLeftMutableImutablePrimitiveEffectedPure"

var _TyProp_index = [...]uint8{0, 7, 14, 20, 25, 31, 36, 41, 45, 50, 54, 61, 69, 78, 86, 90}

func (i TyProp) String() string {
	if i < 0 || i >= TyProp(len(_TyProp_index)-1) {
		return "TyProp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TyProp_name[_TyProp_index[i]:_TyProp_index[i+1]]
}
