// Code generated by "stringer -type=TyTok"; DO NOT EDIT.

package functions

import "strconv"

const _TyTok_name = "Tok_TextTok_NumberTok_SymbolTok_KeywordTok_OperatorTok_DelimiterTok_SeperatorTok_PunktationTok_DefinitionTok_ParametricTok_NatTypeTok_FncTypeTok_Context"

var _TyTok_index = [...]uint8{0, 8, 18, 28, 39, 51, 64, 77, 91, 105, 119, 130, 141, 152}

func (i TyTok) String() string {
	if i >= TyTok(len(_TyTok_index)-1) {
		return "TyTok(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TyTok_name[_TyTok_index[i]:_TyTok_index[i+1]]
}
