// Code generated by "stringer -type=TyTok"; DO NOT EDIT.

package functions

import "strconv"

const _TyTok_name = "Tok_TextTok_FncTypeTok_NatTypeTok_ParamTypeTok_ClassType"

var _TyTok_index = [...]uint8{0, 8, 19, 30, 43, 56}

func (i TyTok) String() string {
	if i >= TyTok(len(_TyTok_index)-1) {
		return "TyTok(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TyTok_name[_TyTok_index[i]:_TyTok_index[i+1]]
}
