// Code generated by "stringer -type Comp"; DO NOT EDIT.

package gatw

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Sum-0]
	_ = x[Product-1]
}

const _Comp_name = "SumProduct"

var _Comp_index = [...]uint8{0, 3, 10}

func (i Comp) String() string {
	if i < 0 || i >= Comp(len(_Comp_index)-1) {
		return "Comp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Comp_name[_Comp_index[i]:_Comp_index[i+1]]
}
