// Code generated by "stringer -type Fixity"; DO NOT EDIT.

package gatw

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Infix-0]
	_ = x[Prefix-1]
	_ = x[Postfix-3]
}

const (
	_Fixity_name_0 = "InfixPrefix"
	_Fixity_name_1 = "Postfix"
)

var (
	_Fixity_index_0 = [...]uint8{0, 5, 11}
)

func (i Fixity) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _Fixity_name_0[_Fixity_index_0[i]:_Fixity_index_0[i+1]]
	case i == 3:
		return _Fixity_name_1
	default:
		return "Fixity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
