// Code generated by "stringer -type Option"; DO NOT EDIT.

package gatw

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Either-0]
	_ = x[Or-1]
}

const _Option_name = "EitherOr"

var _Option_index = [...]uint8{0, 6, 8}

func (i Option) String() string {
	if i < 0 || i >= Option(len(_Option_index)-1) {
		return "Option(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Option_name[_Option_index[i]:_Option_index[i+1]]
}
