// Code generated by "stringer -type Rank"; DO NOT EDIT.

package gatw

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Lesser - -1]
	_ = x[Equal-0]
	_ = x[Greater-1]
}

const _Rank_name = "LesserEqualGreater"

var _Rank_index = [...]uint8{0, 6, 11, 18}

func (i Rank) String() string {
	i -= -1
	if i < 0 || i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
