// Code generated by "stringer -type TC"; DO NOT EDIT.

package gatw

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[N-0]
	_ = x[Type-1]
	_ = x[Func-3]
	_ = x[Symb-7]
}

const (
	_TC_name_0 = "NType"
	_TC_name_1 = "Func"
	_TC_name_2 = "Symb"
)

var (
	_TC_index_0 = [...]uint8{0, 1, 5}
)

func (i TC) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _TC_name_0[_TC_index_0[i]:_TC_index_0[i+1]]
	case i == 3:
		return _TC_name_1
	case i == 7:
		return _TC_name_2
	default:
		return "TC(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
