// Code generated by "stringer -type tflg"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Truth-1]
	_ = x[Uint-3]
	_ = x[Int-7]
	_ = x[Flt-15]
	_ = x[Img-31]
	_ = x[Time-63]
	_ = x[Span-127]
	_ = x[Byte-255]
	_ = x[Rune-511]
	_ = x[Bytes-1023]
	_ = x[String-2047]
	_ = x[Vector-4095]
	_ = x[Tuple-8191]
	_ = x[List-16383]
	_ = x[Zero-32767]
	_ = x[One-65535]
	_ = x[Min-131071]
	_ = x[Max-262143]
	_ = x[Fnc-524287]
	_ = x[Op-1048575]
	_ = x[Just-2097151]
	_ = x[Either-4194303]
	_ = x[Or-8388607]
}

const _tflg_name = "NoneTruthUintIntFltImgTimeSpanByteRuneBytesStringVectorTupleListZeroOneMinMaxFncOpJustEitherOr"

var _tflg_map = map[tflg]string{
	0:       _tflg_name[0:4],
	1:       _tflg_name[4:9],
	3:       _tflg_name[9:13],
	7:       _tflg_name[13:16],
	15:      _tflg_name[16:19],
	31:      _tflg_name[19:22],
	63:      _tflg_name[22:26],
	127:     _tflg_name[26:30],
	255:     _tflg_name[30:34],
	511:     _tflg_name[34:38],
	1023:    _tflg_name[38:43],
	2047:    _tflg_name[43:49],
	4095:    _tflg_name[49:55],
	8191:    _tflg_name[55:60],
	16383:   _tflg_name[60:64],
	32767:   _tflg_name[64:68],
	65535:   _tflg_name[68:71],
	131071:  _tflg_name[71:74],
	262143:  _tflg_name[74:77],
	524287:  _tflg_name[77:80],
	1048575: _tflg_name[80:82],
	2097151: _tflg_name[82:86],
	4194303: _tflg_name[86:92],
	8388607: _tflg_name[92:94],
}

func (i tflg) String() string {
	if str, ok := _tflg_map[i]; ok {
		return str
	}
	return "tflg(" + strconv.FormatInt(int64(i), 10) + ")"
}
