// Code generated by "stringer -type tflg"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Truth-1]
	_ = x[Uint-3]
	_ = x[Int-7]
	_ = x[Flt-15]
	_ = x[Img-31]
	_ = x[Time-63]
	_ = x[Span-127]
	_ = x[Byte-255]
	_ = x[Rune-511]
	_ = x[Bytes-1023]
	_ = x[String-2047]
	_ = x[Vector-4095]
	_ = x[Tuple-8191]
	_ = x[List-16383]
	_ = x[Fnc-32767]
	_ = x[Op-65535]
	_ = x[Just-131071]
	_ = x[Either-262143]
	_ = x[Or-524287]
}

const _tflg_name = "NoneTruthUintIntFltImgTimeSpanByteRuneBytesStringVectorTupleListFncOpJustEitherOr"

var _tflg_map = map[tflg]string{
	0:      _tflg_name[0:4],
	1:      _tflg_name[4:9],
	3:      _tflg_name[9:13],
	7:      _tflg_name[13:16],
	15:     _tflg_name[16:19],
	31:     _tflg_name[19:22],
	63:     _tflg_name[22:26],
	127:    _tflg_name[26:30],
	255:    _tflg_name[30:34],
	511:    _tflg_name[34:38],
	1023:   _tflg_name[38:43],
	2047:   _tflg_name[43:49],
	4095:   _tflg_name[49:55],
	8191:   _tflg_name[55:60],
	16383:  _tflg_name[60:64],
	32767:  _tflg_name[64:67],
	65535:  _tflg_name[67:69],
	131071: _tflg_name[69:73],
	262143: _tflg_name[73:79],
	524287: _tflg_name[79:81],
}

func (i tflg) String() string {
	if str, ok := _tflg_map[i]; ok {
		return str
	}
	return "tflg(" + strconv.FormatInt(int64(i), 10) + ")"
}
