// Code generated by "stringer -type ArgPosition"; DO NOT EDIT.

package types

import "strconv"

const _ArgPosition_name = "ReturnType"

var _ArgPosition_index = [...]uint8{0, 10}

func (i ArgPosition) String() string {
	if i < 0 || i >= ArgPosition(len(_ArgPosition_index)-1) {
		return "ArgPosition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArgPosition_name[_ArgPosition_index[i]:_ArgPosition_index[i+1]]
}
