// Code generated by "stringer -type Arity"; DO NOT EDIT.

package types

import "strconv"

const _Arity_name = "NullaryUnaryBinaryTrinaryTernaryQuaternaryQuinarySenarySeptenaryOctonaryNovenaryDenaryPolyadic"

var _Arity_index = [...]uint8{0, 7, 12, 18, 25, 32, 42, 49, 55, 64, 72, 80, 86, 94}

func (i Arity) String() string {
	if i < 0 || i >= Arity(len(_Arity_index)-1) {
		return "Arity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Arity_name[_Arity_index[i]:_Arity_index[i+1]]
}
