// Code generated by "stringer -type ColProps"; DO NOT EDIT.

package types

import "strconv"

const (
	_ColProps_name_0 = "Reverse"
	_ColProps_name_1 = "Lambda"
	_ColProps_name_2 = "Eager"
)

func (i ColProps) String() string {
	switch {
	case i == 2305843009213693952:
		return _ColProps_name_0
	case i == 4611686018427387904:
		return _ColProps_name_1
	case i == 9223372036854775808:
		return _ColProps_name_2
	default:
		return "ColProps(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
