// Code generated by "stringer -type=Fixity"; DO NOT EDIT.

package types

import "strconv"

const _Fixity_name = "PreFix"

var _Fixity_index = [...]uint8{0, 6}

func (i Fixity) String() string {
	i -= -1
	if i < 0 || i >= Fixity(len(_Fixity_index)-1) {
		return "Fixity(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Fixity_name[_Fixity_index[i]:_Fixity_index[i+1]]
}
