// Code generated by "stringer -type FixType"; DO NOT EDIT.

package types

import "strconv"

const _FixType_name = "PreFixInFixPostFixConstantFixNil"

var _FixType_index = [...]uint8{0, 6, 11, 18, 26, 32}

func (i FixType) String() string {
	i -= 13
	if i >= FixType(len(_FixType_index)-1) {
		return "FixType(" + strconv.FormatInt(int64(i+13), 10) + ")"
	}
	return _FixType_name[_FixType_index[i]:_FixType_index[i+1]]
}
