// Code generated by "stringer -type=FnType"; DO NOT EDIT.

package types

import "strconv"

const (
	_FnType_name_0 = "StateFuncParamFunc"
	_FnType_name_1 = "ConstFunc"
	_FnType_name_2 = "UnaryFunc"
	_FnType_name_3 = "BinaryFunc"
	_FnType_name_4 = "NnaryFunc"
	_FnType_name_5 = "PrediFunc"
	_FnType_name_6 = "SetoidFunc"
)

var (
	_FnType_index_0 = [...]uint8{0, 9, 18}
)

func (i FnType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _FnType_name_0[_FnType_index_0[i]:_FnType_index_0[i+1]]
	case i == 4:
		return _FnType_name_1
	case i == 8:
		return _FnType_name_2
	case i == 16:
		return _FnType_name_3
	case i == 32:
		return _FnType_name_4
	case i == 64:
		return _FnType_name_5
	case i == 128:
		return _FnType_name_6
	default:
		return "FnType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
