// Code generated by "stringer -type=FnType"; DO NOT EDIT.

package types

import "strconv"

const _FnType_name = "StateFuncParamFunc"

var _FnType_index = [...]uint8{0, 9, 18}

func (i FnType) String() string {
	i -= 1
	if i >= FnType(len(_FnType_index)-1) {
		return "FnType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FnType_name[_FnType_index[i]:_FnType_index[i+1]]
}
