// Code generated by "stringer -type NodeT"; DO NOT EDIT.

package types

import "strconv"

const (
	_NodeT_name_0 = "NodeRoot"
	_NodeT_name_1 = "NodeChainNodeBranchNodeNestNodeLeave"
)

var (
	_NodeT_index_1 = [...]uint8{0, 9, 19, 27, 36}
)

func (i NodeT) String() string {
	switch {
	case i == 0:
		return _NodeT_name_0
	case 2 <= i && i <= 5:
		i -= 2
		return _NodeT_name_1[_NodeT_index_1[i]:_NodeT_index_1[i+1]]
	default:
		return "NodeT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
