// Code generated by "stringer -type=TypeClass"; DO NOT EDIT.

package types

import "strconv"

const _TypeClass_name = "metaTypeNamedataConstructortypeConstructortypeConverterfunctionSignaturefunctionBody"

var _TypeClass_index = [...]uint8{0, 12, 27, 42, 55, 72, 84}

func (i TypeClass) String() string {
	if i >= TypeClass(len(_TypeClass_index)-1) {
		return "TypeClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeClass_name[_TypeClass_index[i]:_TypeClass_index[i+1]]
}
