// Code generated by "stringer -type=ValType"; DO NOT EDIT.

package types

import "strconv"

const _ValType_name = "NilBoolIntInt8Int16Int32BigIntUintUint16Uint32FloatFlt32BigFltImagImag64ByteBytesStringTimeDurationErrorCellAttrChainListLinkDLinkAttrListUniSetAttrSetRecordTupleNodeTreeFunctionNATIVE"

var _ValType_map = map[ValType]string{
	0:           _ValType_name[0:3],
	1:           _ValType_name[3:7],
	4:           _ValType_name[7:10],
	8:           _ValType_name[10:14],
	16:          _ValType_name[14:19],
	32:          _ValType_name[19:24],
	64:          _ValType_name[24:30],
	128:         _ValType_name[30:34],
	256:         _ValType_name[34:40],
	512:         _ValType_name[40:46],
	1024:        _ValType_name[46:51],
	2048:        _ValType_name[51:56],
	4096:        _ValType_name[56:62],
	8192:        _ValType_name[62:66],
	16384:       _ValType_name[66:72],
	32768:       _ValType_name[72:76],
	65536:       _ValType_name[76:81],
	131072:      _ValType_name[81:87],
	262144:      _ValType_name[87:91],
	524288:      _ValType_name[91:99],
	1048576:     _ValType_name[99:104],
	2097152:     _ValType_name[104:108],
	4194304:     _ValType_name[108:112],
	8388608:     _ValType_name[112:117],
	16777216:    _ValType_name[117:121],
	33554432:    _ValType_name[121:125],
	67108864:    _ValType_name[125:130],
	134217728:   _ValType_name[130:138],
	268435456:   _ValType_name[138:144],
	536870912:   _ValType_name[144:151],
	1073741824:  _ValType_name[151:157],
	2147483648:  _ValType_name[157:162],
	4294967296:  _ValType_name[162:166],
	8589934592:  _ValType_name[166:170],
	17179869184: _ValType_name[170:178],
	34359738368: _ValType_name[178:184],
}

func (i ValType) String() string {
	if str, ok := _ValType_map[i]; ok {
		return str
	}
	return "ValType(" + strconv.FormatInt(int64(i), 10) + ")"
}
