// Code generated by "stringer -type=ValType"; DO NOT EDIT.

package types

import "strconv"

const _ValType_name = "NilBoolIntInt8Int16Int32UintUint16Uint32FloatFlt32ComplexComplex64ByteBytesStringErrorElemFieldListMuliListMapMuliSetRecordLinkedDLinkedTupleTupNTupTTupATNodeTreeFuncIdentTypeId"

var _ValType_map = map[ValType]string{
	0:           _ValType_name[0:3],
	2:           _ValType_name[3:7],
	4:           _ValType_name[7:10],
	8:           _ValType_name[10:14],
	16:          _ValType_name[14:19],
	32:          _ValType_name[19:24],
	64:          _ValType_name[24:28],
	128:         _ValType_name[28:34],
	256:         _ValType_name[34:40],
	512:         _ValType_name[40:45],
	1024:        _ValType_name[45:50],
	2048:        _ValType_name[50:57],
	4096:        _ValType_name[57:66],
	8192:        _ValType_name[66:70],
	16384:       _ValType_name[70:75],
	32768:       _ValType_name[75:81],
	65536:       _ValType_name[81:86],
	131072:      _ValType_name[86:90],
	262144:      _ValType_name[90:95],
	524288:      _ValType_name[95:99],
	1048576:     _ValType_name[99:107],
	2097152:     _ValType_name[107:110],
	4194304:     _ValType_name[110:117],
	8388608:     _ValType_name[117:123],
	16777216:    _ValType_name[123:129],
	33554432:    _ValType_name[129:136],
	67108864:    _ValType_name[136:141],
	134217728:   _ValType_name[141:145],
	268435456:   _ValType_name[145:149],
	536870912:   _ValType_name[149:154],
	1073741824:  _ValType_name[154:158],
	2147483648:  _ValType_name[158:162],
	4294967296:  _ValType_name[162:166],
	8589934592:  _ValType_name[166:171],
	17179869184: _ValType_name[171:177],
}

func (i ValType) String() string {
	if str, ok := _ValType_map[i]; ok {
		return str
	}
	return "ValType(" + strconv.FormatInt(int64(i), 10) + ")"
}
