// Code generated by "stringer -type=ValType"; DO NOT EDIT.

package types

import "strconv"

const _ValType_name = "NilMetaTypeBoolIntInt8Int16Int32BigIntUintUint16Uint32FloatFlt32BigFltImagImag64ByteBytesStringTimeDurationErrorAttrChainListLinkDLinkAttrListUniSetAttrSetRecordCellTupleNodeTreeFunctionNATIVE"

var _ValType_map = map[ValType]string{
	0:           _ValType_name[0:3],
	1:           _ValType_name[3:11],
	4:           _ValType_name[11:15],
	8:           _ValType_name[15:18],
	16:          _ValType_name[18:22],
	32:          _ValType_name[22:27],
	64:          _ValType_name[27:32],
	128:         _ValType_name[32:38],
	256:         _ValType_name[38:42],
	512:         _ValType_name[42:48],
	1024:        _ValType_name[48:54],
	2048:        _ValType_name[54:59],
	4096:        _ValType_name[59:64],
	8192:        _ValType_name[64:70],
	16384:       _ValType_name[70:74],
	32768:       _ValType_name[74:80],
	65536:       _ValType_name[80:84],
	131072:      _ValType_name[84:89],
	262144:      _ValType_name[89:95],
	524288:      _ValType_name[95:99],
	1048576:     _ValType_name[99:107],
	2097152:     _ValType_name[107:112],
	4194304:     _ValType_name[112:116],
	8388608:     _ValType_name[116:121],
	16777216:    _ValType_name[121:125],
	33554432:    _ValType_name[125:129],
	67108864:    _ValType_name[129:134],
	134217728:   _ValType_name[134:142],
	268435456:   _ValType_name[142:148],
	536870912:   _ValType_name[148:155],
	1073741824:  _ValType_name[155:161],
	2147483648:  _ValType_name[161:165],
	4294967296:  _ValType_name[165:170],
	8589934592:  _ValType_name[170:174],
	17179869184: _ValType_name[174:178],
	34359738368: _ValType_name[178:186],
	68719476736: _ValType_name[186:192],
}

func (i ValType) String() string {
	if str, ok := _ValType_map[i]; ok {
		return str
	}
	return "ValType(" + strconv.FormatInt(int64(i), 10) + ")"
}
