// Code generated by "stringer -type=TyTok"; DO NOT EDIT.

package parser

import "strconv"

const _TyTok_name = "Tok_BlankTok_TextTok_NumberTok_SymbolTok_KeywordTok_OperatorTok_DelimiterTok_SeperatorTok_PunktationTok_DefTypeTok_NatTypeTok_FncTypeTok_Context"

var _TyTok_index = [...]uint8{0, 9, 17, 27, 37, 48, 60, 73, 86, 100, 111, 122, 133, 144}

func (i TyTok) String() string {
	if i >= TyTok(len(_TyTok_index)-1) {
		return "TyTok(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TyTok_name[_TyTok_index[i]:_TyTok_index[i+1]]
}
