// Code generated by "stringer -type=SyntaxItemFlag"; DO NOT EDIT.

package lex

import "strconv"

const _SyntaxItemFlag_name = "NoneErrorBlankUnderscoreAsteriskDotCommaColonSemicolonMinusPlusOrXorAndEqualLesserGreaterLesseqGreaterqLeftParRightParLeftBraRightBraLeftCurRightCurSlashPipeNotUnequalDecIncDoubEqualTripEqualRightArrowLeftArrowFatLArrowFatRArrowDoubColSing_quoteDoub_quoteBackSlashLambdaFunctionPolymorphNumberText"

var _SyntaxItemFlag_map = map[SyntaxItemFlag]string{
	0:              _SyntaxItemFlag_name[0:4],
	1:              _SyntaxItemFlag_name[4:9],
	4:              _SyntaxItemFlag_name[9:14],
	8:              _SyntaxItemFlag_name[14:24],
	16:             _SyntaxItemFlag_name[24:32],
	32:             _SyntaxItemFlag_name[32:35],
	64:             _SyntaxItemFlag_name[35:40],
	128:            _SyntaxItemFlag_name[40:45],
	256:            _SyntaxItemFlag_name[45:54],
	512:            _SyntaxItemFlag_name[54:59],
	1024:           _SyntaxItemFlag_name[59:63],
	2048:           _SyntaxItemFlag_name[63:65],
	4096:           _SyntaxItemFlag_name[65:68],
	8192:           _SyntaxItemFlag_name[68:71],
	16384:          _SyntaxItemFlag_name[71:76],
	32768:          _SyntaxItemFlag_name[76:82],
	65536:          _SyntaxItemFlag_name[82:89],
	131072:         _SyntaxItemFlag_name[89:95],
	262144:         _SyntaxItemFlag_name[95:103],
	524288:         _SyntaxItemFlag_name[103:110],
	1048576:        _SyntaxItemFlag_name[110:118],
	2097152:        _SyntaxItemFlag_name[118:125],
	4194304:        _SyntaxItemFlag_name[125:133],
	8388608:        _SyntaxItemFlag_name[133:140],
	16777216:       _SyntaxItemFlag_name[140:148],
	33554432:       _SyntaxItemFlag_name[148:153],
	67108864:       _SyntaxItemFlag_name[153:157],
	134217728:      _SyntaxItemFlag_name[157:160],
	268435456:      _SyntaxItemFlag_name[160:167],
	536870912:      _SyntaxItemFlag_name[167:170],
	1073741824:     _SyntaxItemFlag_name[170:173],
	2147483648:     _SyntaxItemFlag_name[173:182],
	4294967296:     _SyntaxItemFlag_name[182:191],
	8589934592:     _SyntaxItemFlag_name[191:201],
	17179869184:    _SyntaxItemFlag_name[201:210],
	34359738368:    _SyntaxItemFlag_name[210:219],
	68719476736:    _SyntaxItemFlag_name[219:228],
	137438953472:   _SyntaxItemFlag_name[228:235],
	274877906944:   _SyntaxItemFlag_name[235:245],
	549755813888:   _SyntaxItemFlag_name[245:255],
	1099511627776:  _SyntaxItemFlag_name[255:264],
	2199023255552:  _SyntaxItemFlag_name[264:270],
	4398046511104:  _SyntaxItemFlag_name[270:278],
	8796093022208:  _SyntaxItemFlag_name[278:287],
	17592186044416: _SyntaxItemFlag_name[287:293],
	35184372088832: _SyntaxItemFlag_name[293:297],
}

func (i SyntaxItemFlag) String() string {
	if str, ok := _SyntaxItemFlag_map[i]; ok {
		return str
	}
	return "SyntaxItemFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
