// Code generated by "stringer -type=SyntaxItemFlag"; DO NOT EDIT.

package lex

import "strconv"

const _SyntaxItemFlag_name = "NoneBlankTabNewLineUnderscoreSquareRootAsteriskFullstopCommaColonSemicolonSubstractionAdditionDotTimesDotProductCrossProductDivisionInfiniteOrXorAndEqualLesserGreaterLesserEqGreaterEqLeftParRightParLeftBraRightBraLeftCurRightCurSlashPipeNotUnequalDecrementIncrementDoubleEqualTripEqualRightArrowLeftArrowFatLArrowFatRArrowDoubColSing_quoteDoub_quoteBackSlashLambdaFunctionPolymorphMonadParameterSequenceSequenceRevIntegralIsMemberEmptySetNumberTextEtaEpsilon"

var _SyntaxItemFlag_map = map[SyntaxItemFlag]string{
	0:                   _SyntaxItemFlag_name[0:4],
	1:                   _SyntaxItemFlag_name[4:9],
	4:                   _SyntaxItemFlag_name[9:12],
	8:                   _SyntaxItemFlag_name[12:19],
	16:                  _SyntaxItemFlag_name[19:29],
	32:                  _SyntaxItemFlag_name[29:39],
	64:                  _SyntaxItemFlag_name[39:47],
	128:                 _SyntaxItemFlag_name[47:55],
	256:                 _SyntaxItemFlag_name[55:60],
	512:                 _SyntaxItemFlag_name[60:65],
	1024:                _SyntaxItemFlag_name[65:74],
	2048:                _SyntaxItemFlag_name[74:86],
	4096:                _SyntaxItemFlag_name[86:94],
	8192:                _SyntaxItemFlag_name[94:97],
	16384:               _SyntaxItemFlag_name[97:102],
	32768:               _SyntaxItemFlag_name[102:112],
	65536:               _SyntaxItemFlag_name[112:124],
	131072:              _SyntaxItemFlag_name[124:132],
	262144:              _SyntaxItemFlag_name[132:140],
	524288:              _SyntaxItemFlag_name[140:142],
	1048576:             _SyntaxItemFlag_name[142:145],
	2097152:             _SyntaxItemFlag_name[145:148],
	4194304:             _SyntaxItemFlag_name[148:153],
	8388608:             _SyntaxItemFlag_name[153:159],
	16777216:            _SyntaxItemFlag_name[159:166],
	33554432:            _SyntaxItemFlag_name[166:174],
	67108864:            _SyntaxItemFlag_name[174:183],
	134217728:           _SyntaxItemFlag_name[183:190],
	268435456:           _SyntaxItemFlag_name[190:198],
	536870912:           _SyntaxItemFlag_name[198:205],
	1073741824:          _SyntaxItemFlag_name[205:213],
	2147483648:          _SyntaxItemFlag_name[213:220],
	4294967296:          _SyntaxItemFlag_name[220:228],
	8589934592:          _SyntaxItemFlag_name[228:233],
	17179869184:         _SyntaxItemFlag_name[233:237],
	34359738368:         _SyntaxItemFlag_name[237:240],
	68719476736:         _SyntaxItemFlag_name[240:247],
	137438953472:        _SyntaxItemFlag_name[247:256],
	274877906944:        _SyntaxItemFlag_name[256:265],
	549755813888:        _SyntaxItemFlag_name[265:276],
	1099511627776:       _SyntaxItemFlag_name[276:285],
	2199023255552:       _SyntaxItemFlag_name[285:295],
	4398046511104:       _SyntaxItemFlag_name[295:304],
	8796093022208:       _SyntaxItemFlag_name[304:313],
	17592186044416:      _SyntaxItemFlag_name[313:322],
	35184372088832:      _SyntaxItemFlag_name[322:329],
	70368744177664:      _SyntaxItemFlag_name[329:339],
	140737488355328:     _SyntaxItemFlag_name[339:349],
	281474976710656:     _SyntaxItemFlag_name[349:358],
	562949953421312:     _SyntaxItemFlag_name[358:364],
	1125899906842624:    _SyntaxItemFlag_name[364:372],
	2251799813685248:    _SyntaxItemFlag_name[372:381],
	4503599627370496:    _SyntaxItemFlag_name[381:386],
	9007199254740992:    _SyntaxItemFlag_name[386:395],
	18014398509481984:   _SyntaxItemFlag_name[395:403],
	36028797018963968:   _SyntaxItemFlag_name[403:414],
	72057594037927936:   _SyntaxItemFlag_name[414:422],
	144115188075855872:  _SyntaxItemFlag_name[422:430],
	288230376151711744:  _SyntaxItemFlag_name[430:438],
	576460752303423488:  _SyntaxItemFlag_name[438:444],
	1152921504606846976: _SyntaxItemFlag_name[444:448],
	2305843009213693952: _SyntaxItemFlag_name[448:451],
	4611686018427387904: _SyntaxItemFlag_name[451:458],
}

func (i SyntaxItemFlag) String() string {
	if str, ok := _SyntaxItemFlag_map[i]; ok {
		return str
	}
	return "SyntaxItemFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
