// Code generated by "stringer -type=SyntaxItemFlag"; DO NOT EDIT.

package lex

import "strconv"

const _SyntaxItemFlag_name = "NoneErrorBlankTabNewLineUnderscoreSquareRootAsteriskFullstopCommaColonSemicolonSubstractionAdditionDotTimesDotProductCrossProductDivisionInfiniteOrXorAndEqualLesserGreaterLesserEqGreaterEqLeftParRightParLeftBraRightBraLeftCurRightCurSlashPipeNotUnequalDecrementIncrementDoubEqualTripEqualRightArrowLeftArrowFatLArrowFatRArrowDoubColSing_quoteDoub_quoteBackSlashLambdaFunctionPolymorphNumberText"

var _SyntaxItemFlag_map = map[SyntaxItemFlag]string{
	0:                 _SyntaxItemFlag_name[0:4],
	1:                 _SyntaxItemFlag_name[4:9],
	4:                 _SyntaxItemFlag_name[9:14],
	8:                 _SyntaxItemFlag_name[14:17],
	16:                _SyntaxItemFlag_name[17:24],
	32:                _SyntaxItemFlag_name[24:34],
	64:                _SyntaxItemFlag_name[34:44],
	128:               _SyntaxItemFlag_name[44:52],
	256:               _SyntaxItemFlag_name[52:60],
	512:               _SyntaxItemFlag_name[60:65],
	1024:              _SyntaxItemFlag_name[65:70],
	2048:              _SyntaxItemFlag_name[70:79],
	4096:              _SyntaxItemFlag_name[79:91],
	8192:              _SyntaxItemFlag_name[91:99],
	16384:             _SyntaxItemFlag_name[99:102],
	32768:             _SyntaxItemFlag_name[102:107],
	65536:             _SyntaxItemFlag_name[107:117],
	131072:            _SyntaxItemFlag_name[117:129],
	262144:            _SyntaxItemFlag_name[129:137],
	524288:            _SyntaxItemFlag_name[137:145],
	1048576:           _SyntaxItemFlag_name[145:147],
	2097152:           _SyntaxItemFlag_name[147:150],
	4194304:           _SyntaxItemFlag_name[150:153],
	8388608:           _SyntaxItemFlag_name[153:158],
	16777216:          _SyntaxItemFlag_name[158:164],
	33554432:          _SyntaxItemFlag_name[164:171],
	67108864:          _SyntaxItemFlag_name[171:179],
	134217728:         _SyntaxItemFlag_name[179:188],
	268435456:         _SyntaxItemFlag_name[188:195],
	536870912:         _SyntaxItemFlag_name[195:203],
	1073741824:        _SyntaxItemFlag_name[203:210],
	2147483648:        _SyntaxItemFlag_name[210:218],
	4294967296:        _SyntaxItemFlag_name[218:225],
	8589934592:        _SyntaxItemFlag_name[225:233],
	17179869184:       _SyntaxItemFlag_name[233:238],
	34359738368:       _SyntaxItemFlag_name[238:242],
	68719476736:       _SyntaxItemFlag_name[242:245],
	137438953472:      _SyntaxItemFlag_name[245:252],
	274877906944:      _SyntaxItemFlag_name[252:261],
	549755813888:      _SyntaxItemFlag_name[261:270],
	1099511627776:     _SyntaxItemFlag_name[270:279],
	2199023255552:     _SyntaxItemFlag_name[279:288],
	4398046511104:     _SyntaxItemFlag_name[288:298],
	8796093022208:     _SyntaxItemFlag_name[298:307],
	17592186044416:    _SyntaxItemFlag_name[307:316],
	35184372088832:    _SyntaxItemFlag_name[316:325],
	70368744177664:    _SyntaxItemFlag_name[325:332],
	140737488355328:   _SyntaxItemFlag_name[332:342],
	281474976710656:   _SyntaxItemFlag_name[342:352],
	562949953421312:   _SyntaxItemFlag_name[352:361],
	1125899906842624:  _SyntaxItemFlag_name[361:367],
	2251799813685248:  _SyntaxItemFlag_name[367:375],
	4503599627370496:  _SyntaxItemFlag_name[375:384],
	9007199254740992:  _SyntaxItemFlag_name[384:390],
	18014398509481984: _SyntaxItemFlag_name[390:394],
}

func (i SyntaxItemFlag) String() string {
	if str, ok := _SyntaxItemFlag_map[i]; ok {
		return str
	}
	return "SyntaxItemFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
