// Code generated by "stringer -type=TySyntax"; DO NOT EDIT.

package lex

import "strconv"

const _TySyntax_name = "NoneBlankTabNewLineUnderscoreSquareRootAsteriskFullstopEllipsisSubstractionAdditionDotTimesDotProductCrossProductDivisionInfiniteOrXorAndEqualLesserGreaterLesserEqGreaterEqLeftParRightParLeftBraRightBraLeftCurRightCurSlashPipeNotUnequalDecrementIncrementDoubleEqualTripEqualRightArrowLeftArrowFatLArrowFatRArrowDoubColSingQuoteDoubQuoteBackTickBackSlashLambdaFunctionPolymorphMonadParameterSequenceSequenceRevIntegralIsMemberEmptySetNumberTextEtaEpsilon"

var _TySyntax_map = map[TySyntax]string{
	0:                   _TySyntax_name[0:4],
	1:                   _TySyntax_name[4:9],
	4:                   _TySyntax_name[9:12],
	8:                   _TySyntax_name[12:19],
	16:                  _TySyntax_name[19:29],
	32:                  _TySyntax_name[29:39],
	64:                  _TySyntax_name[39:47],
	128:                 _TySyntax_name[47:55],
	256:                 _TySyntax_name[55:63],
	512:                 _TySyntax_name[63:75],
	1024:                _TySyntax_name[75:83],
	2048:                _TySyntax_name[83:86],
	4096:                _TySyntax_name[86:91],
	8192:                _TySyntax_name[91:101],
	16384:               _TySyntax_name[101:113],
	32768:               _TySyntax_name[113:121],
	65536:               _TySyntax_name[121:129],
	131072:              _TySyntax_name[129:131],
	262144:              _TySyntax_name[131:134],
	524288:              _TySyntax_name[134:137],
	1048576:             _TySyntax_name[137:142],
	2097152:             _TySyntax_name[142:148],
	4194304:             _TySyntax_name[148:155],
	8388608:             _TySyntax_name[155:163],
	16777216:            _TySyntax_name[163:172],
	33554432:            _TySyntax_name[172:179],
	67108864:            _TySyntax_name[179:187],
	134217728:           _TySyntax_name[187:194],
	268435456:           _TySyntax_name[194:202],
	536870912:           _TySyntax_name[202:209],
	1073741824:          _TySyntax_name[209:217],
	2147483648:          _TySyntax_name[217:222],
	4294967296:          _TySyntax_name[222:226],
	8589934592:          _TySyntax_name[226:229],
	17179869184:         _TySyntax_name[229:236],
	34359738368:         _TySyntax_name[236:245],
	68719476736:         _TySyntax_name[245:254],
	137438953472:        _TySyntax_name[254:265],
	274877906944:        _TySyntax_name[265:274],
	549755813888:        _TySyntax_name[274:284],
	1099511627776:       _TySyntax_name[284:293],
	2199023255552:       _TySyntax_name[293:302],
	4398046511104:       _TySyntax_name[302:311],
	8796093022208:       _TySyntax_name[311:318],
	17592186044416:      _TySyntax_name[318:327],
	35184372088832:      _TySyntax_name[327:336],
	70368744177664:      _TySyntax_name[336:344],
	140737488355328:     _TySyntax_name[344:353],
	281474976710656:     _TySyntax_name[353:359],
	562949953421312:     _TySyntax_name[359:367],
	1125899906842624:    _TySyntax_name[367:376],
	2251799813685248:    _TySyntax_name[376:381],
	4503599627370496:    _TySyntax_name[381:390],
	9007199254740992:    _TySyntax_name[390:398],
	18014398509481984:   _TySyntax_name[398:409],
	36028797018963968:   _TySyntax_name[409:417],
	72057594037927936:   _TySyntax_name[417:425],
	144115188075855872:  _TySyntax_name[425:433],
	288230376151711744:  _TySyntax_name[433:439],
	576460752303423488:  _TySyntax_name[439:443],
	1152921504606846976: _TySyntax_name[443:446],
	2305843009213693952: _TySyntax_name[446:453],
}

func (i TySyntax) String() string {
	if str, ok := _TySyntax_map[i]; ok {
		return str
	}
	return "TySyntax(" + strconv.FormatInt(int64(i), 10) + ")"
}
