// Code generated by "stringer -type=TyNative"; DO NOT EDIT.

package data

import "strconv"

const _TyNative_name = "NilBoolInt8Int16Int32IntBigIntUint8Uint16Uint32UintFlt32FloatBigFltRatioImag64ImagTimeDurationByteRuneBytesStringReaderWriterPipeErrorNatFncSumProdPairTupleRecordVectorListSetDataFunctionInstanceFlagMAX_INT"

var _TyNative_map = map[TyNative]string{
	1:                    _TyNative_name[0:3],
	2:                    _TyNative_name[3:7],
	4:                    _TyNative_name[7:11],
	8:                    _TyNative_name[11:16],
	16:                   _TyNative_name[16:21],
	32:                   _TyNative_name[21:24],
	64:                   _TyNative_name[24:30],
	128:                  _TyNative_name[30:35],
	256:                  _TyNative_name[35:41],
	512:                  _TyNative_name[41:47],
	1024:                 _TyNative_name[47:51],
	2048:                 _TyNative_name[51:56],
	4096:                 _TyNative_name[56:61],
	8192:                 _TyNative_name[61:67],
	16384:                _TyNative_name[67:72],
	32768:                _TyNative_name[72:78],
	65536:                _TyNative_name[78:82],
	131072:               _TyNative_name[82:86],
	262144:               _TyNative_name[86:94],
	524288:               _TyNative_name[94:98],
	1048576:              _TyNative_name[98:102],
	2097152:              _TyNative_name[102:107],
	4194304:              _TyNative_name[107:113],
	8388608:              _TyNative_name[113:119],
	16777216:             _TyNative_name[119:125],
	33554432:             _TyNative_name[125:129],
	67108864:             _TyNative_name[129:134],
	134217728:            _TyNative_name[134:137],
	268435456:            _TyNative_name[137:140],
	536870912:            _TyNative_name[140:143],
	1073741824:           _TyNative_name[143:147],
	2147483648:           _TyNative_name[147:151],
	4294967296:           _TyNative_name[151:156],
	8589934592:           _TyNative_name[156:162],
	17179869184:          _TyNative_name[162:168],
	34359738368:          _TyNative_name[168:172],
	68719476736:          _TyNative_name[172:175],
	137438953472:         _TyNative_name[175:179],
	274877906944:         _TyNative_name[179:187],
	549755813888:         _TyNative_name[187:195],
	1099511627776:        _TyNative_name[195:199],
	18446744073709551615: _TyNative_name[199:206],
}

func (i TyNative) String() string {
	if str, ok := _TyNative_map[i]; ok {
		return str
	}
	return "TyNative(" + strconv.FormatInt(int64(i), 10) + ")"
}
