// Code generated by "stringer -type=TyNative"; DO NOT EDIT.

package data

import "strconv"

const _TyNative_name = "NilBoolInt8Int16Int32IntBigIntUint8Uint16Uint32UintFlt32FloatBigFltRatioImag64ImagTimeDurationByteRuneBytesStringErrorNatFncSumProdPairTupleRecordVectorListSetFunctionFlagMAX_INT"

var _TyNative_map = map[TyNative]string{
	1:                    _TyNative_name[0:3],
	2:                    _TyNative_name[3:7],
	4:                    _TyNative_name[7:11],
	8:                    _TyNative_name[11:16],
	16:                   _TyNative_name[16:21],
	32:                   _TyNative_name[21:24],
	64:                   _TyNative_name[24:30],
	128:                  _TyNative_name[30:35],
	256:                  _TyNative_name[35:41],
	512:                  _TyNative_name[41:47],
	1024:                 _TyNative_name[47:51],
	2048:                 _TyNative_name[51:56],
	4096:                 _TyNative_name[56:61],
	8192:                 _TyNative_name[61:67],
	16384:                _TyNative_name[67:72],
	32768:                _TyNative_name[72:78],
	65536:                _TyNative_name[78:82],
	131072:               _TyNative_name[82:86],
	262144:               _TyNative_name[86:94],
	524288:               _TyNative_name[94:98],
	1048576:              _TyNative_name[98:102],
	2097152:              _TyNative_name[102:107],
	4194304:              _TyNative_name[107:113],
	8388608:              _TyNative_name[113:118],
	16777216:             _TyNative_name[118:121],
	33554432:             _TyNative_name[121:124],
	67108864:             _TyNative_name[124:127],
	134217728:            _TyNative_name[127:131],
	268435456:            _TyNative_name[131:135],
	536870912:            _TyNative_name[135:140],
	1073741824:           _TyNative_name[140:146],
	2147483648:           _TyNative_name[146:152],
	4294967296:           _TyNative_name[152:156],
	8589934592:           _TyNative_name[156:159],
	17179869184:          _TyNative_name[159:167],
	34359738368:          _TyNative_name[167:171],
	18446744073709551615: _TyNative_name[171:178],
}

func (i TyNative) String() string {
	if str, ok := _TyNative_map[i]; ok {
		return str
	}
	return "TyNative(" + strconv.FormatInt(int64(i), 10) + ")"
}
