// Code generated by "stringer -type=TyNative"; DO NOT EDIT.

package data

import "strconv"

const _TyNative_name = "NilBoolInt8Int16Int32IntBigIntUint8Uint16Uint32UintFlt32FloatBigFltRatioImag64ImagTimeDurationByteRuneBytesStringPipeBufferReaderWriterChannelErrorNatFncSumProdPairTupleRecordVectorListSetDataExpressionFunctionInstanceFlagMASK"

var _TyNative_map = map[TyNative]string{
	1:                    _TyNative_name[0:3],
	2:                    _TyNative_name[3:7],
	4:                    _TyNative_name[7:11],
	8:                    _TyNative_name[11:16],
	16:                   _TyNative_name[16:21],
	32:                   _TyNative_name[21:24],
	64:                   _TyNative_name[24:30],
	128:                  _TyNative_name[30:35],
	256:                  _TyNative_name[35:41],
	512:                  _TyNative_name[41:47],
	1024:                 _TyNative_name[47:51],
	2048:                 _TyNative_name[51:56],
	4096:                 _TyNative_name[56:61],
	8192:                 _TyNative_name[61:67],
	16384:                _TyNative_name[67:72],
	32768:                _TyNative_name[72:78],
	65536:                _TyNative_name[78:82],
	131072:               _TyNative_name[82:86],
	262144:               _TyNative_name[86:94],
	524288:               _TyNative_name[94:98],
	1048576:              _TyNative_name[98:102],
	2097152:              _TyNative_name[102:107],
	4194304:              _TyNative_name[107:113],
	8388608:              _TyNative_name[113:117],
	16777216:             _TyNative_name[117:123],
	33554432:             _TyNative_name[123:129],
	67108864:             _TyNative_name[129:135],
	134217728:            _TyNative_name[135:142],
	268435456:            _TyNative_name[142:147],
	536870912:            _TyNative_name[147:150],
	1073741824:           _TyNative_name[150:153],
	2147483648:           _TyNative_name[153:156],
	4294967296:           _TyNative_name[156:160],
	8589934592:           _TyNative_name[160:164],
	17179869184:          _TyNative_name[164:169],
	34359738368:          _TyNative_name[169:175],
	68719476736:          _TyNative_name[175:181],
	137438953472:         _TyNative_name[181:185],
	274877906944:         _TyNative_name[185:188],
	549755813888:         _TyNative_name[188:192],
	1099511627776:        _TyNative_name[192:202],
	2199023255552:        _TyNative_name[202:210],
	4398046511104:        _TyNative_name[210:218],
	8796093022208:        _TyNative_name[218:222],
	18446744073709551615: _TyNative_name[222:226],
}

func (i TyNative) String() string {
	if str, ok := _TyNative_map[i]; ok {
		return str
	}
	return "TyNative(" + strconv.FormatInt(int64(i), 10) + ")"
}
