// Code generated by "stringer -type=Type"; DO NOT EDIT.

package data

import "strconv"

const _Type_name = "NilBoolInt8Int16Int32IntBigIntUint8Uint16Uint32UintFlt32FloatBigFltRatioImag64ImagTimeDurationByteRuneBytesStringErrorPairTupleRecordVectorListSetArgumentParameterFunctionObjectFlagMAX_INT"

var _Type_map = map[Type]string{
	1:                    _Type_name[0:3],
	2:                    _Type_name[3:7],
	4:                    _Type_name[7:11],
	8:                    _Type_name[11:16],
	16:                   _Type_name[16:21],
	32:                   _Type_name[21:24],
	64:                   _Type_name[24:30],
	128:                  _Type_name[30:35],
	256:                  _Type_name[35:41],
	512:                  _Type_name[41:47],
	1024:                 _Type_name[47:51],
	2048:                 _Type_name[51:56],
	4096:                 _Type_name[56:61],
	8192:                 _Type_name[61:67],
	16384:                _Type_name[67:72],
	32768:                _Type_name[72:78],
	65536:                _Type_name[78:82],
	131072:               _Type_name[82:86],
	262144:               _Type_name[86:94],
	524288:               _Type_name[94:98],
	1048576:              _Type_name[98:102],
	2097152:              _Type_name[102:107],
	4194304:              _Type_name[107:113],
	8388608:              _Type_name[113:118],
	16777216:             _Type_name[118:122],
	33554432:             _Type_name[122:127],
	67108864:             _Type_name[127:133],
	134217728:            _Type_name[133:139],
	268435456:            _Type_name[139:143],
	536870912:            _Type_name[143:146],
	1073741824:           _Type_name[146:154],
	2147483648:           _Type_name[154:163],
	4294967296:           _Type_name[163:171],
	8589934592:           _Type_name[171:177],
	17179869184:          _Type_name[177:181],
	18446744073709551615: _Type_name[181:188],
}

func (i Type) String() string {
	if str, ok := _Type_map[i]; ok {
		return str
	}
	return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
}
