// Code generated by "stringer -type=TyPrime"; DO NOT EDIT.

package data

import "strconv"

const _TyPrime_name = "NilBoolInt8Int16Int32IntBigIntUint8Uint16Uint32UintFlt32FloatBigFltRatioImag64ImagTimeDurationByteRuneBytesStringErrorTypeEnumPairTupleRecordVectorListSetFunctionFlagMAX_INT"

var _TyPrime_map = map[TyPrime]string{
	1:                    _TyPrime_name[0:3],
	2:                    _TyPrime_name[3:7],
	4:                    _TyPrime_name[7:11],
	8:                    _TyPrime_name[11:16],
	16:                   _TyPrime_name[16:21],
	32:                   _TyPrime_name[21:24],
	64:                   _TyPrime_name[24:30],
	128:                  _TyPrime_name[30:35],
	256:                  _TyPrime_name[35:41],
	512:                  _TyPrime_name[41:47],
	1024:                 _TyPrime_name[47:51],
	2048:                 _TyPrime_name[51:56],
	4096:                 _TyPrime_name[56:61],
	8192:                 _TyPrime_name[61:67],
	16384:                _TyPrime_name[67:72],
	32768:                _TyPrime_name[72:78],
	65536:                _TyPrime_name[78:82],
	131072:               _TyPrime_name[82:86],
	262144:               _TyPrime_name[86:94],
	524288:               _TyPrime_name[94:98],
	1048576:              _TyPrime_name[98:102],
	2097152:              _TyPrime_name[102:107],
	4194304:              _TyPrime_name[107:113],
	8388608:              _TyPrime_name[113:118],
	16777216:             _TyPrime_name[118:122],
	33554432:             _TyPrime_name[122:126],
	67108864:             _TyPrime_name[126:130],
	134217728:            _TyPrime_name[130:135],
	268435456:            _TyPrime_name[135:141],
	536870912:            _TyPrime_name[141:147],
	1073741824:           _TyPrime_name[147:151],
	2147483648:           _TyPrime_name[151:154],
	4294967296:           _TyPrime_name[154:162],
	8589934592:           _TyPrime_name[162:166],
	18446744073709551615: _TyPrime_name[166:173],
}

func (i TyPrime) String() string {
	if str, ok := _TyPrime_map[i]; ok {
		return str
	}
	return "TyPrime(" + strconv.FormatInt(int64(i), 10) + ")"
}
