// Code generated by "stringer -type=TypeItem"; DO NOT EDIT.

package lang

import "strconv"

const _TypeItem_name = "NoneBlankUnderscoreAsteriskDotCommaColonSemicolonMinusPlusOrXorAndEqualLesserGreaterLesseqGreaterqLeftParRightParLeftBraRightBraLeftCurRightCurSlashPipeNotUnequalDecIncDoubEqualTripEqualRightArrowLeftArrowFatLArrowFatRArrowDoubColSing_quoteDoub_quoteBckSlaLambdaGenTypeHeadWordTailWordInWordConWordLetWordMutableWordWhereWordOtherwiseWordIfWordThenWordElseWordCaseWordOfWordDataWordTypeWordNumberLetterCapitalFuncIdentTypeIdent"

var _TypeItem_map = map[TypeItem]string{
	1:                   _TypeItem_name[0:4],
	2:                   _TypeItem_name[4:9],
	4:                   _TypeItem_name[9:19],
	8:                   _TypeItem_name[19:27],
	16:                  _TypeItem_name[27:30],
	32:                  _TypeItem_name[30:35],
	64:                  _TypeItem_name[35:40],
	128:                 _TypeItem_name[40:49],
	256:                 _TypeItem_name[49:54],
	512:                 _TypeItem_name[54:58],
	1024:                _TypeItem_name[58:60],
	2048:                _TypeItem_name[60:63],
	4096:                _TypeItem_name[63:66],
	8192:                _TypeItem_name[66:71],
	16384:               _TypeItem_name[71:77],
	32768:               _TypeItem_name[77:84],
	65536:               _TypeItem_name[84:90],
	131072:              _TypeItem_name[90:98],
	262144:              _TypeItem_name[98:105],
	524288:              _TypeItem_name[105:113],
	1048576:             _TypeItem_name[113:120],
	2097152:             _TypeItem_name[120:128],
	4194304:             _TypeItem_name[128:135],
	8388608:             _TypeItem_name[135:143],
	16777216:            _TypeItem_name[143:148],
	33554432:            _TypeItem_name[148:152],
	67108864:            _TypeItem_name[152:155],
	134217728:           _TypeItem_name[155:162],
	268435456:           _TypeItem_name[162:165],
	536870912:           _TypeItem_name[165:168],
	1073741824:          _TypeItem_name[168:177],
	2147483648:          _TypeItem_name[177:186],
	4294967296:          _TypeItem_name[186:196],
	8589934592:          _TypeItem_name[196:205],
	17179869184:         _TypeItem_name[205:214],
	34359738368:         _TypeItem_name[214:223],
	68719476736:         _TypeItem_name[223:230],
	137438953472:        _TypeItem_name[230:240],
	274877906944:        _TypeItem_name[240:250],
	549755813888:        _TypeItem_name[250:256],
	1099511627776:       _TypeItem_name[256:262],
	2199023255552:       _TypeItem_name[262:269],
	4398046511104:       _TypeItem_name[269:277],
	8796093022208:       _TypeItem_name[277:285],
	17592186044416:      _TypeItem_name[285:291],
	35184372088832:      _TypeItem_name[291:298],
	70368744177664:      _TypeItem_name[298:305],
	140737488355328:     _TypeItem_name[305:316],
	281474976710656:     _TypeItem_name[316:325],
	562949953421312:     _TypeItem_name[325:338],
	1125899906842624:    _TypeItem_name[338:344],
	2251799813685248:    _TypeItem_name[344:352],
	4503599627370496:    _TypeItem_name[352:360],
	9007199254740992:    _TypeItem_name[360:368],
	18014398509481984:   _TypeItem_name[368:374],
	36028797018963968:   _TypeItem_name[374:382],
	72057594037927936:   _TypeItem_name[382:390],
	144115188075855872:  _TypeItem_name[390:396],
	288230376151711744:  _TypeItem_name[396:402],
	576460752303423488:  _TypeItem_name[402:409],
	1152921504606846976: _TypeItem_name[409:418],
	2305843009213693952: _TypeItem_name[418:427],
}

func (i TypeItem) String() string {
	if str, ok := _TypeItem_map[i]; ok {
		return str
	}
	return "TypeItem(" + strconv.FormatInt(int64(i), 10) + ")"
}
