// Code generated by "stringer -type Layout"; DO NOT EDIT.

package run

import "strconv"

const _Layout_name = "Arg0Arg1Arg2Arg3Arg4Arg5Arg6Arg7Arg8Arg9Arg10Arg11Arg12Arg13Arg14Arg15Arg16Arg17Arg18Arg19Arg20Arg21Arg22Arg23Arg24Arg25Arg26Arg27Arg28Arg29Arg30Arg31"

var _Layout_map = map[Layout]string{
	1:          _Layout_name[0:4],
	2:          _Layout_name[4:8],
	4:          _Layout_name[8:12],
	8:          _Layout_name[12:16],
	16:         _Layout_name[16:20],
	32:         _Layout_name[20:24],
	64:         _Layout_name[24:28],
	128:        _Layout_name[28:32],
	256:        _Layout_name[32:36],
	512:        _Layout_name[36:40],
	1024:       _Layout_name[40:45],
	2048:       _Layout_name[45:50],
	4096:       _Layout_name[50:55],
	8192:       _Layout_name[55:60],
	16384:      _Layout_name[60:65],
	32768:      _Layout_name[65:70],
	65536:      _Layout_name[70:75],
	131072:     _Layout_name[75:80],
	262144:     _Layout_name[80:85],
	524288:     _Layout_name[85:90],
	1048576:    _Layout_name[90:95],
	2097152:    _Layout_name[95:100],
	4194304:    _Layout_name[100:105],
	8388608:    _Layout_name[105:110],
	16777216:   _Layout_name[110:115],
	33554432:   _Layout_name[115:120],
	67108864:   _Layout_name[120:125],
	134217728:  _Layout_name[125:130],
	268435456:  _Layout_name[130:135],
	536870912:  _Layout_name[135:140],
	1073741824: _Layout_name[140:145],
	2147483648: _Layout_name[145:150],
}

func (i Layout) String() string {
	if str, ok := _Layout_map[i]; ok {
		return str
	}
	return "Layout(" + strconv.FormatInt(int64(i), 10) + ")"
}
