// Code generated by "stringer -type=Otype"; DO NOT EDIT.

package run

import "strconv"

const _Otype_name = "PartialApplicationCallContinuationCaseContinuationDataConstructorFunctionCallDeclarationIndirectionBlackHoleByteCodeThunkSystemThreadSharedAsyncSync"

var _Otype_map = map[Otype]string{
	1:     _Otype_name[0:18],
	2:     _Otype_name[18:34],
	4:     _Otype_name[34:50],
	8:     _Otype_name[50:65],
	16:    _Otype_name[65:77],
	32:    _Otype_name[77:88],
	64:    _Otype_name[88:99],
	128:   _Otype_name[99:108],
	256:   _Otype_name[108:116],
	512:   _Otype_name[116:121],
	1024:  _Otype_name[121:127],
	2048:  _Otype_name[127:133],
	4096:  _Otype_name[133:139],
	8192:  _Otype_name[139:144],
	16384: _Otype_name[144:148],
}

func (i Otype) String() string {
	if str, ok := _Otype_map[i]; ok {
		return str
	}
	return "Otype(" + strconv.FormatInt(int64(i), 10) + ")"
}
