// Code generated by "stringer -type Propertys"; DO NOT EDIT.

package run

import "strconv"

const (
	_Propertys_name_0 = "DefaultPostFix"
	_Propertys_name_1 = "InFixAtomicEagerRightMutableSideEffectData"
)

var (
	_Propertys_index_0 = [...]uint8{0, 7, 14}
	_Propertys_index_1 = [...]uint8{0, 5, 11, 16, 21, 28, 38, 42}
)

func (i Propertys) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _Propertys_name_0[_Propertys_index_0[i]:_Propertys_index_0[i+1]]
	case 3 <= i && i <= 9:
		i -= 3
		return _Propertys_name_1[_Propertys_index_1[i]:_Propertys_index_1[i+1]]
	default:
		return "Propertys(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
